##### Source Angular autocompletion after 'nvm use' #####

eval "$(declare -f nvm | sed '1s/nvm/_original_nvm/')"

nvm() {
  _original_nvm "$@"
  if [[ "$1" = "use" && $(hash ng 2>&1) = "" ]]; then
    # Load Angular CLI autocompletion.
    # Disabling SC1090 because the script is generated by Angular CLI and is not a static file.
    # shellcheck disable=SC1090
    source <(ng completion script)
  fi
}
