#!/usr/bin/env bash


{
  printf "\n\n"
  printf "##### Onefetch Git repository greeter #####"
  printf "\n"
  printf "last_repository="
  printf "\n"
  printf "check_directory_for_new_repository() {"
  printf "\n"
  printf "  current_repository=\$(git rev-parse --show-toplevel 2>/dev/null)"
  printf "\n"
  printf "\n"
  printf "  if [ \"\$current_repository\" ] &&"
  printf "\n"
  printf "    [ \"\$current_repository\" != \"\$last_repository\" ]; then"
  printf "\n"
  printf "    onefetch"
  printf "\n"
  printf "  fi"
  printf "\n"
  printf "  last_repository=\"\$current_repository\""
  printf "\n"
  printf "}"
  printf "\n"
  printf "cd() {"
  printf "\n"
  printf "  builtin cd \"\$@\""
  printf "\n"
  printf "  check_directory_for_new_repository"
  printf "\n"
  printf "}"
  printf "\n"
  printf "##### Onefetch Git repository greeter #####"
  printf "\n"
} >> "$ZSHRC_FILE"
